export const ReviewActionTypes = {
  FETCH_PRODUCT_REVIEWS: 'FETCH_PRODUCT_REVIEWS',
  SET_PRODUCT_REVIEWS: 'SET_PRODUCT_REVIEWS',
  DELETE_PRODUCT_REVIEWS: 'DELETE_PRODUCT_REVIEWS',
  ADD_PRODUCT_REVIEWS: 'ADD_PRODUCT_REVIEWS',
};
